/*
 * UberAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 09/30/2016
 */
package com.uber.api.models;

import java.util.*;

public class ErrorsBuilder {
    //the instance to build
    private Errors errors;

    /**
     * Default constructor to initialize the instance
     */
    public ErrorsBuilder() {
        errors = new Errors();
    }

    public ErrorsBuilder code(String code) {
        errors.setCode(code);
        return this;
    }

    public ErrorsBuilder status(int status) {
        errors.setStatus(status);
        return this;
    }

    public ErrorsBuilder title(String title) {
        errors.setTitle(title);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Errors build() {
        return errors;
    }
}