/*
 * UberAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 09/30/2016
 */
package com.uber.api.models;

import java.util.*;

public class GetProductsTypesInputBuilder {
    //the instance to build
    private GetProductsTypesInput getProductsTypesInput;

    /**
     * Default constructor to initialize the instance
     */
    public GetProductsTypesInputBuilder() {
        getProductsTypesInput = new GetProductsTypesInput();
    }

    /**
     * Latitude component of location.
     */
    public GetProductsTypesInputBuilder latitude(double latitude) {
        getProductsTypesInput.setLatitude(latitude);
        return this;
    }

    /**
     * Longitude component of location.
     */
    public GetProductsTypesInputBuilder longitude(double longitude) {
        getProductsTypesInput.setLongitude(longitude);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public GetProductsTypesInput build() {
        return getProductsTypesInput;
    }
}