/*
 * UberAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 09/30/2016
 */
package com.uber.api.models;

import java.util.*;

public class GetPriceEstimatesInputBuilder {
    //the instance to build
    private GetPriceEstimatesInput getPriceEstimatesInput;

    /**
     * Default constructor to initialize the instance
     */
    public GetPriceEstimatesInputBuilder() {
        getPriceEstimatesInput = new GetPriceEstimatesInput();
    }

    /**
     * Latitude component of end location.
     */
    public GetPriceEstimatesInputBuilder endLatitude(double endLatitude) {
        getPriceEstimatesInput.setEndLatitude(endLatitude);
        return this;
    }

    /**
     * Longitude component of end location.
     */
    public GetPriceEstimatesInputBuilder endLongitude(double endLongitude) {
        getPriceEstimatesInput.setEndLongitude(endLongitude);
        return this;
    }

    /**
     * Latitude component of start location.
     */
    public GetPriceEstimatesInputBuilder startLatitude(double startLatitude) {
        getPriceEstimatesInput.setStartLatitude(startLatitude);
        return this;
    }

    /**
     * Longitude component of start location.
     */
    public GetPriceEstimatesInputBuilder startLongitude(double startLongitude) {
        getPriceEstimatesInput.setStartLongitude(startLongitude);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public GetPriceEstimatesInput build() {
        return getPriceEstimatesInput;
    }
}