/*
 * UberAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 09/30/2016
 */
package com.uber.api.models;

import java.util.*;

public class GetTimeEstimatesInputBuilder {
    //the instance to build
    private GetTimeEstimatesInput getTimeEstimatesInput;

    /**
     * Default constructor to initialize the instance
     */
    public GetTimeEstimatesInputBuilder() {
        getTimeEstimatesInput = new GetTimeEstimatesInput();
    }

    /**
     * Latitude component of the start location
     */
    public GetTimeEstimatesInputBuilder startLatitude(double startLatitude) {
        getTimeEstimatesInput.setStartLatitude(startLatitude);
        return this;
    }

    /**
     * Longitude component of the start location
     */
    public GetTimeEstimatesInputBuilder startLongitude(double startLongitude) {
        getTimeEstimatesInput.setStartLongitude(startLongitude);
        return this;
    }

    /**
     * The customer id interested in estimate
     */
    public GetTimeEstimatesInputBuilder customerUuid(String customerUuid) {
        getTimeEstimatesInput.setCustomerUuid(customerUuid);
        return this;
    }

    /**
     * Id of the requested product
     */
    public GetTimeEstimatesInputBuilder productId(String productId) {
        getTimeEstimatesInput.setProductId(productId);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public GetTimeEstimatesInput build() {
        return getTimeEstimatesInput;
    }
}