/*
 * UberAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 09/30/2016
 */
package com.uber.api.models;

import java.util.*;

public class GetUserActivityV11InputBuilder {
    //the instance to build
    private GetUserActivityV11Input getUserActivityV11Input;

    /**
     * Default constructor to initialize the instance
     */
    public GetUserActivityV11InputBuilder() {
        getUserActivityV11Input = new GetUserActivityV11Input();
    }

    /**
     * Number of items to return for pagging
     */
    public GetUserActivityV11InputBuilder limit(int limit) {
        getUserActivityV11Input.setLimit(limit);
        return this;
    }

    /**
     * Page offset for pagging
     */
    public GetUserActivityV11InputBuilder offset(int offset) {
        getUserActivityV11Input.setOffset(offset);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public GetUserActivityV11Input build() {
        return getUserActivityV11Input;
    }
}