/*
 * UberAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 09/30/2016
 */
package com.uber.api.models;

import java.util.*;

public class HistoryBuilder {
    //the instance to build
    private History history;

    /**
     * Default constructor to initialize the instance
     */
    public HistoryBuilder() {
        history = new History();
    }

    /**
     * Distance travelled
     */
    public HistoryBuilder distance(double distance) {
        history.setDistance(distance);
        return this;
    }

    /**
     * Location where journey ended
     */
    public HistoryBuilder endLocation(Location endLocation) {
        history.setEndLocation(endLocation);
        return this;
    }

    /**
     * Time of journey end
     */
    public HistoryBuilder endTime(int endTime) {
        history.setEndTime(endTime);
        return this;
    }

    /**
     * The product that was used
     */
    public HistoryBuilder productId(String productId) {
        history.setProductId(productId);
        return this;
    }

    /**
     * Time when requested
     */
    public HistoryBuilder requestTime(int requestTime) {
        history.setRequestTime(requestTime);
        return this;
    }

    /**
     * Location of starting the journey
     */
    public HistoryBuilder startLocation(Location startLocation) {
        history.setStartLocation(startLocation);
        return this;
    }

    /**
     * Time of starting the journey
     */
    public HistoryBuilder startTime(int startTime) {
        history.setStartTime(startTime);
        return this;
    }

    /**
     * Status of the product e.g., completed
     */
    public HistoryBuilder status(String status) {
        history.setStatus(status);
        return this;
    }

    /**
     * History item id
     */
    public HistoryBuilder uuid(String uuid) {
        history.setUuid(uuid);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public History build() {
        return history;
    }
}