/*
 * UberAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 09/30/2016
 */
package com.uber.api.models;

import java.util.*;

public class LocationBuilder {
    //the instance to build
    private Location location;

    /**
     * Default constructor to initialize the instance
     */
    public LocationBuilder() {
        location = new Location();
    }

    /**
     * The address in user readable form
     */
    public LocationBuilder address(String address) {
        location.setAddress(address);
        return this;
    }

    /**
     * Latitude component of location.
     */
    public LocationBuilder latitude(double latitude) {
        location.setLatitude(latitude);
        return this;
    }

    /**
     * Longitude component of location.
     */
    public LocationBuilder longitude(double longitude) {
        location.setLongitude(longitude);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Location build() {
        return location;
    }
}