/*
 * UberAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 09/30/2016
 */
package com.uber.api.models;

import java.util.*;

public class MetaBuilder {
    //the instance to build
    private Meta meta;

    /**
     * Default constructor to initialize the instance
     */
    public MetaBuilder() {
        meta = new Meta();
    }

    public MetaBuilder surgeConfirmation(SurgeConfirmation surgeConfirmation) {
        meta.setSurgeConfirmation(surgeConfirmation);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Meta build() {
        return meta;
    }
}