/*
 * UberAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 09/30/2016
 */
package com.uber.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class Meta 
        implements java.io.Serializable {
    private static final long serialVersionUID = 5748477714857347342L;
    private SurgeConfirmation surgeConfirmation;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("surge_confirmation")
    public SurgeConfirmation getSurgeConfirmation ( ) { 
        return this.surgeConfirmation;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("surge_confirmation")
    public void setSurgeConfirmation (SurgeConfirmation value) { 
        this.surgeConfirmation = value;
    }
 
}
 