/*
 * UberAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 09/30/2016
 */
package com.uber.api.models;

import java.util.*;

public class ProductBuilder {
    //the instance to build
    private Product product;

    /**
     * Default constructor to initialize the instance
     */
    public ProductBuilder() {
        product = new Product();
    }

    /**
     * Capacity of product. For example, 4 people.
     */
    public ProductBuilder capacity(int capacity) {
        product.setCapacity(capacity);
        return this;
    }

    /**
     * Description of product.
     */
    public ProductBuilder description(String description) {
        product.setDescription(description);
        return this;
    }

    /**
     * Display name of product.
     */
    public ProductBuilder displayName(String displayName) {
        product.setDisplayName(displayName);
        return this;
    }

    /**
     * Image URL representing the product.
     */
    public ProductBuilder image(String image) {
        product.setImage(image);
        return this;
    }

    /**
     * Unique identifier representing a specific product for a given latitude & longitude. For example, uberX in San Francisco will have a different product_id than uberX in Los Angeles.
     */
    public ProductBuilder productId(String productId) {
        product.setProductId(productId);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Product build() {
        return product;
    }
}