/*
 * UberAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 09/30/2016
 */
package com.uber.api.models;

import java.util.*;

public class PromotionsResponseBuilder {
    //the instance to build
    private PromotionsResponse promotionsResponse;

    /**
     * Default constructor to initialize the instance
     */
    public PromotionsResponseBuilder() {
        promotionsResponse = new PromotionsResponse();
    }

    /**
     * A localized string we recommend to use when offering the promotion to users.
     */
    public PromotionsResponseBuilder displayText(String displayText) {
        promotionsResponse.setDisplayText(displayText);
        return this;
    }

    /**
     * The value of the promotion that is available to a user in this location in the local currency.
     */
    public PromotionsResponseBuilder localizedValue(String localizedValue) {
        promotionsResponse.setLocalizedValue(localizedValue);
        return this;
    }

    /**
     * The type of the promo which is either "trip_credit" or "account_credit".
     */
    public PromotionsResponseBuilder type(String type) {
        promotionsResponse.setType(type);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public PromotionsResponse build() {
        return promotionsResponse;
    }
}