/*
 * UberAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 09/30/2016
 */
package com.uber.api.models;

import java.util.*;

public class RequestBodyBuilder {
    //the instance to build
    private RequestBody requestBody;

    /**
     * Default constructor to initialize the instance
     */
    public RequestBodyBuilder() {
        requestBody = new RequestBody();
    }

    /**
     * The final or destination latitude.
     */
    public RequestBodyBuilder endLatitude(double endLatitude) {
        requestBody.setEndLatitude(endLatitude);
        return this;
    }

    /**
     * The final or destination longitude.
     */
    public RequestBodyBuilder endLongitude(double endLongitude) {
        requestBody.setEndLongitude(endLongitude);
        return this;
    }

    /**
     * The unique ID of the product being requested.
     */
    public RequestBodyBuilder productId(String productId) {
        requestBody.setProductId(productId);
        return this;
    }

    /**
     * The beginning or "pickup" latitude.
     */
    public RequestBodyBuilder startLatitude(double startLatitude) {
        requestBody.setStartLatitude(startLatitude);
        return this;
    }

    /**
     * The beginning or "pickup" longitude.
     */
    public RequestBodyBuilder startLongitude(double startLongitude) {
        requestBody.setStartLongitude(startLongitude);
        return this;
    }

    /**
     * The unique identifier of the surge session for a user. Required when returned from a 409 Conflict response on previous POST attempt.
     */
    public RequestBodyBuilder surgeConfirmationId(String surgeConfirmationId) {
        requestBody.setSurgeConfirmationId(surgeConfirmationId);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public RequestBody build() {
        return requestBody;
    }
}