/*
 * UberAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 09/30/2016
 */
package com.uber.api.models;

import java.util.*;

public class SurgeConfirmationBuilder {
    //the instance to build
    private SurgeConfirmation surgeConfirmation;

    /**
     * Default constructor to initialize the instance
     */
    public SurgeConfirmationBuilder() {
        surgeConfirmation = new SurgeConfirmation();
    }

    public SurgeConfirmationBuilder href(String href) {
        surgeConfirmation.setHref(href);
        return this;
    }

    public SurgeConfirmationBuilder surgeConfirmationId(String surgeConfirmationId) {
        surgeConfirmation.setSurgeConfirmationId(surgeConfirmationId);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public SurgeConfirmation build() {
        return surgeConfirmation;
    }
}