/*
 * UberAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 09/30/2016
 */
package com.uber.api.models;

import java.util.*;

public class TimeEstimateBuilder {
    //the instance to build
    private TimeEstimate timeEstimate;

    /**
     * Default constructor to initialize the instance
     */
    public TimeEstimateBuilder() {
        timeEstimate = new TimeEstimate();
    }

    /**
     * Display name of product.
     */
    public TimeEstimateBuilder displayName(String displayName) {
        timeEstimate.setDisplayName(displayName);
        return this;
    }

    /**
     * ETA for the product (in seconds). Always show estimate in minutes.
     */
    public TimeEstimateBuilder estimate(int estimate) {
        timeEstimate.setEstimate(estimate);
        return this;
    }

    /**
     * Unique identifier representing a specific product for a given latitude & longitude. For example, uberX in San Francisco will have a different product_id than uberX in Los Angeles.
     */
    public TimeEstimateBuilder productId(String productId) {
        timeEstimate.setProductId(productId);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public TimeEstimate build() {
        return timeEstimate;
    }
}