/*
 * UberAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 09/30/2016
 */
package com.uber.api.models;

import java.util.*;

public class VehicleBuilder {
    //the instance to build
    private Vehicle vehicle;

    /**
     * Default constructor to initialize the instance
     */
    public VehicleBuilder() {
        vehicle = new Vehicle();
    }

    public VehicleBuilder licensePlate(String licensePlate) {
        vehicle.setLicensePlate(licensePlate);
        return this;
    }

    public VehicleBuilder make(String make) {
        vehicle.setMake(make);
        return this;
    }

    public VehicleBuilder model(String model) {
        vehicle.setModel(model);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Vehicle build() {
        return vehicle;
    }
}